// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGzXD2yoIX5zF7weVGw8J1QdRmTnQB1GQ',
    appId: '1:1013728946079:web:4f8dcc941bb59bb0e03faa',
    messagingSenderId: '1013728946079',
    projectId: 'cast-app-f34dd',
    authDomain: 'cast-app-f34dd.firebaseapp.com',
    storageBucket: 'cast-app-f34dd.appspot.com',
    measurementId: 'G-B8MP3DWSWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ8oDEqmHObzdVJV6lNhy0N9MxsWspVnk',
    appId: '1:1013728946079:android:da3678ce37cb09fde03faa',
    messagingSenderId: '1013728946079',
    projectId: 'cast-app-f34dd',
    storageBucket: 'cast-app-f34dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4fdfwwXlVQ_PrCkF4ZQVOFxNcYkNlzs0',
    appId: '1:1013728946079:ios:7267a03b5aa5410ae03faa',
    messagingSenderId: '1013728946079',
    projectId: 'cast-app-f34dd',
    storageBucket: 'cast-app-f34dd.appspot.com',
    iosBundleId: 'com.cast.castapp',
  );
}
